"use server";

import { auth, currentUser } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";
import { createAdminClient } from "@/lib/supabase/admin";

export async function createFirstBusiness(
  name: string = "Mi negocio",
  _type: string = "course"
) {
  const { userId } = await auth();
  if (!userId) throw new Error("No autenticado");

  const user = await currentUser();
  const email = user?.emailAddresses?.[0]?.emailAddress ?? "";
  const fullName = [user?.firstName, user?.lastName].filter(Boolean).join(" ");

  const supabase = createAdminClient();

  // Upsert user by clerk_id (text); id is a UUID auto-generated by Supabase
  const { data: userData, error: userError } = await supabase
    .from("users")
    .upsert(
      {
        clerk_id: userId,
        email,
        name: fullName || null,
      },
      { onConflict: "clerk_id" }
    )
    .select("id")
    .single();

  if (userError) throw new Error(userError.message);

  // owner_id expects the UUID from users.id, not the Clerk text id
  const { data: businessData, error } = await supabase
    .from("businesses")
    .insert({ owner_id: userData.id, name })
    .select("id")
    .single();

  if (error) throw new Error(error.message);

  redirect(`/mis-negocios/${businessData.id}`);
}
